name: Continuous Integration

# 1. Trigger
on:
  pull_request:
    branches: [ "main" ]

# 2. Environment & Steps
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Mengambil kode dari repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Menyiapkan bahasa pemrograman (Contoh: Node.js)
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # Menginstal dependensi
    - name: Install dependencies
      working-directory: web
      run: npm install

    # Menjalankan script test
    - name: Run tests
      run: npm test